### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [nightlionsecurity/phpstress#1]
I am a developer for the ArchAssault project, we would like to distribute this project but I noticed its missing a license file. Can you add a license to it and add a git tag for release? We would prefer to pull from  a git tag if possible?

**Comment by vinnytroia** [comment]
done. 

Regards, 

Vinny Troia
@VinnyTroia

**Comment by archey** [comment]
Thanks I wil get it built and let you know when we are ready to release. Most likely it will be by the end of the day.

**Comment by archey** [comment]
this can be closed now as its released
